name: Java CI with Maven

on:
  workflow_dispatch: 
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.6
    - name: Build All Widgets
      uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1.0.1
      with:
       run: mvn -V -B clean verify -Dtycho.localArtifacts=ignore
#    - name: Build Incubation Widgets
#      run: xvfb-run mvn -V clean verify -Pincubation  -Dtycho.localArtifacts=ignore
#    - name: Publish Unit Test Results
#      uses: EnricoMi/publish-unit-test-result-action@v1
#      if: always()
#      with:
#       files: /**/surefire-reports/*.xml
